---
apiVersion: automationcontroller.ansible.com/v1beta1
kind: AutomationController
metadata:
  name: acm-hub-aap
  namespace: aap
  annotations:
    argocd.argoproj.io/sync-wave: '2'
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  create_preload_data: false
  route_tls_termination_mechanism: Edge
  ingress_type: route
  service_type: ClusterIP
  garbage_collect_secrets: false
  image_pull_policy: IfNotPresent
  projects_storage_size: 12Gi
  task_privileged: false
  projects_storage_access_mode: ReadWriteMany
  projects_persistence: true
  projects_use_existing_claim: _No_
  projects_storage_class: ocs-external-storagecluster-cephfs
  replicas: 1
  admin_user: admin
  admin_email: admin@signal9.gg
  admin_password_secret: aap-admin-password
  secret_key_secret: aap-secret-key
  bundle_cacert_secret: app-ca-trust
  route_host: aap.apps.rhte-acm-hub.lab.signal9.gg
  hostname: aap.apps.rhte-acm-hub.lab.signal9.gg
  # Customize EE images due to pull error
  control_plane_ee_image: registry.redhat.io/ansible-automation-platform-23/ee-supported-rhel8@sha256:c1012c02b5e6a2d6130a2a903bed6290eacd25cf6aeb1cb68395a29f911d0b6f
  ee_images:
    - name: supported-ee
      image: registry.redhat.io/ansible-automation-platform-23/ee-supported-rhel8@sha256:c1012c02b5e6a2d6130a2a903bed6290eacd25cf6aeb1cb68395a29f911d0b6f
    - name: supported-minimal
      image: registry.redhat.io/ansible-automation-platform-23/ee-minimal-rhel8@sha256:5c520b468f7f423059363e4397927c2ace498bcdc658340619159fdaf0d4fc01
    - name: supported-2.9
      image: registry.redhat.io/ansible-automation-platform-23/ee-29-rhel8@sha256:3414db39974a6ae20dd7947f18ab9072d69d9d6877aa4d0e0c0bd3e1ada295a7
