apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aap-admin-password
  namespace: aap
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: '1'
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: aap-admin-password
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: rhte-aap-admin
