apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aap-managedcluster-view-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aap-managedcluster-view
subjects:
- kind: ServiceAccount
  name: acm-hub-aap
  namespace: aap
