kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aap-managedcluster-view
rules:
  - verbs:
      - get
      - list
    apiGroups:
      - 'cluster.open-cluster-management.io'
    resources:
      - managedclusters

  - verbs:
      - get
      - list
    apiGroups:
      - ''
    resources:
      - namespaces

