{{- if and .Values.certManager.enabled .Values.certManager.defaultIngressCert -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: apps-certificate
  namespace: openshift-ingress
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "2"
spec:
  secretName: acme-apps
  duration: 2160h0m0s # 90d
  renewBefore: 360h0m0s # 15d
  subject:
    organizations:
    - "Signal9 Labs"
  privateKey:
    size: 4096
    algorithm: RSA
    encoding: PKCS1
    rotationPolicy: Always
  usages:
    - server auth
    - client auth
  dnsNames:
    - "*.apps.{{ .Values.cluster.name }}.{{ .Values.cluster.baseDomain }}"
  issuerRef:
    name: cluster-acme
    kind: ClusterIssuer
{{ end }}
