{{- if .Values.certManager.enabled -}}
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager-operator
  labels:
    openshift.io/cluster-monitoring: 'true'
  annotations:
    argocd.argoproj.io/sync-wave: '-2'
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    openshift.io/cluster-monitoring: 'true'
  annotations:
    argocd.argoproj.io/sync-wave: '-2'

{{ end }}
