apiVersion: logging.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: instance
  namespace: openshift-logging
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  outputs:
  - name: remote-loki
    type: loki
    url: http://172.18.18.12:3100
  pipelines:
  - inputRefs:
    - application
    - infrastructure
    - audit
    name: forward-to-remote
    outputRefs:
    - remote-loki
