apiVersion: v1
kind: ConfigMap
metadata:
  name: vrli-fluent-config
  namespace: vmware-system-vrli
data:
  fluent.conf: |
    <source>
      @type forward
      port 24224
      bind 0.0.0.0
    </source>
    <filter ocp.cluster>
      @type record_transformer
      <record>
        ocp_cluster demo-feb9
      </record>
    </filter>
    <match **>
      @type vmware_loginsight
      scheme https
      ssl_verify false
      host xna-vli.lab.signal9.gg
      port 9543
      http_method post
      serializer json
      rate_limit_msec 0
      raise_on_error true
      include_tag_key true
      tag_key tag
      http_conn_debug false
    </match>
