---
apiVersion: v1
kind: Namespace
metadata:
  name: vmware-system-vrli
  annotations:
    openshift.io/node-selector: ''
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    k8s-app: fluentd-loginsight-logging
  name: fluentd-loginsight-logging
  namespace: vmware-system-vrli
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentd-vrli-clusterrole
rules:
  - apiGroups:
      - ""
    resources:
      - "namespaces"
      - "pods"
    verbs:
      - "list"
      - "get"
      - "watch"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentd-vrli-clusterrole
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluentd-vrli-clusterrole
subjects:
- kind: ServiceAccount
  name: fluentd-loginsight-logging
  namespace: vmware-system-vrli
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluentd-vrli-logging
  namespace: vmware-system-vrli
  labels:
    k8s-app: fluentd-loginsight-logging
    app: fluentd-loginsight-logging
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
 selector:
   matchLabels:
     name: fluentd-loginsight-logging
 replicas: 2
 template:
   metadata:
     labels:
       name: fluentd-loginsight-logging
       app: fluentd-loginsight-logging
       version: v1
       kubernetes.io/cluster-service: "true"
   spec:
     serviceAccount: fluentd-loginsight-logging
     serviceAccountName: fluentd-loginsight-logging
     tolerations:
     - key: node-role.kubernetes.io/master
       effect: NoSchedule
     containers:
     - name: fluentd-vrli
       image: projects.registry.vmware.com/vrealize_loginsight/fluentd:1.1
       command: ["fluentd", "-c", "/etc/fluentd/fluent.conf", "-p", "/fluentd/plugins"]
       env:
       - name: FLUENTD_ARGS
         value: --no-supervisor -q
       ports:
       - name: fluentd-tcp
         containerPort: 24224
       - name: fluentd-udp
         containerPort: 24224
       resources:
         limits:
           memory: 500Mi
         requests:
           cpu: 100m
           memory: 200Mi
       volumeMounts:
       - name: config-volume
         mountPath: /etc/fluentd
     volumes:
     - name: config-volume
       configMap:
         name: vrli-fluent-config
---
apiVersion: v1
kind: Service
metadata:
  name: fluentd-loginsight-logging
  namespace: vmware-system-vrli
spec:
  selector:
    app: fluentd-loginsight-logging
  ports:
    - protocol: TCP
      port: 24224
      name: fluentd-tcp
      targetPort: 24224
    - protocol: UDP
      port: 24224
      name: fluentd-udp
      targetPort: 24224
