apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: managed-cluster-configs
  namespace: openshift-gitops
spec:
  generators:
  - git:
      repoURL: "https://github.com/marbindrakon/rhte-2023-fleet-gitops.git"
      revision: HEAD
      directories:
      - path: argocd/clusters/managed-clusters/*
  template:
    metadata:
      name: "{{ path.basename }}"-managed
    spec:
      project: default
      syncPolicy:
        automated: {}
      destination:
        namespace: openshift-gitops
        server: "{{ path.basename }}"
      source:
        repoURL: "https://github.com/marbindrakon/rhte-2023-fleet-gitops.git"
        targetRevision: HEAD
        path: "{{ path }}"
