cluster:
  name: rhte-acm-hub
  baseDomain: lab.signal9.gg
  gitOpsRepo: https://github.com/marbindrakon/rhte-2023-fleet-gitops.git
  gitOpsBasePath: argocd/clusters
  trustedCABundle: ""

externalSecrets:
  enabled: true
  vaultBase: 'https://vault.lab.signal9.gg'
  vaultAuthPath: 'k8s-ocp'
  secretBasePath: lab/rht-shared

certManager:
  enabled: true
  apiCert: true
  defaultIngressCert: true
  acmeBase: 'https://acme-v02.api.letsencrypt.org/directory'
  externalSecret:
    name: route53-key
    vaultName: signal9-route53
  solvers:
    - http01:
        ingress: {}
    - dns01:
        route53:
          accessKeyID: REDACTED
          region: us-east-1
          secretAccessKeySecretRef:
            key: secret-access-key
            name: route53-key
      selector:
        dnsZones:
          - signal9.gg
          - lab.signal9.gg

monitoring:
  enabled: true
  storageClass: standard

network:
  hostRouting: false

odfStorage:
  enabled: false
  version: '4.11'
  external: false
  externalSecret:
    name: rook-ceph-external-cluster-details
    vaultName: rhte-acm-hub-rook-data

auth:
  enabled: true
  oidcDisplayName: Signal9-RHT
  oidcClientID: openshift
  oidcIssuer: https://login.home.signal9.gg/auth/realms/Signal9-RHT
  externalSecret:
    name: oauth-signal9-client-secret
    vaultName: signal9-openid

timesync:
  enabled: true
  ptp:
    enabled: false
    loadKvmModule: false
    device: 'ptp_kvm'
    sourceStratum: 2
  ntpServers:
    - 172.18.0.79
    - 172.18.42.10
    - 172.18.42.11
