- hosts: localhost
  gather_facts: false
  vars:
    cluster_platform: openstack
    cluster_name: shift-stack-test
    openstack_platform_config:
      vip_network: lab-net
  tasks:
    - name: include resource_allocation role
      ansible.builtin.include_role:
        name: resource_allocation
      vars:
        cluster_state: present
    - name: debug internal VIPs
      ansible.builtin.debug:
        msg: "Internal: API: {{ internal_api_vip }}  Ingess: {{ internal_ingress_vip }}"
    - name: debug external VIPs
      ansible.builtin.debug:
        msg: "External: API: {{ external_api_vip }}  Ingess: {{ external_ingress_vip }}"
    - name: include resource_allocation role
      ansible.builtin.include_role:
        name: resource_allocation
      vars:
        cluster_state: absent
    - name: debug internal VIPs
      ansible.builtin.debug:
        msg: "Internal: API: {{ internal_api_vip }}  Ingess: {{ internal_ingress_vip }}"
    - name: debug external VIPs
      ansible.builtin.debug:
        msg: "External: API: {{ external_api_vip }}  Ingess: {{ external_ingress_vip }}"
