- hosts: localhost
  gather_facts: true
  tasks:
  - name: Get Vault JWT
    no_log: true
    ansible.builtin.set_fact:
      vault_jwt: "{{ lookup('ansible.builtin.file', hashicorp_vault['jwt_location']) }}"
  - name: Dump test secret
    ansible.builtin.debug: 
      msg: "{{ lookup('community.hashi_vault.hashi_vault', 'lab/rht-shared/data/test-openid-secret', auth_method='jwt', mount_point=hashicorp_vault['auth_mount'], role_id=hashicorp_vault['auth_role'], jwt=vault_jwt, url=hashicorp_vault['url']) }}"
