apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: base-config-chart
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: "https://kubernetes.default.svc"
  project: default
  syncPolicy:
    automated: {}
  source:
    repoURL: "https://github.com/marbindrakon/rhte-2023-fleet-gitops.git"
    path: "charts/ocp-base-config"
    targetRevision: master
    helm:
      values: |
        cluster:
          name: rhte-acm-hub
          baseDomain: lab.signal9.gg
        externalSecrets:
          vaultAuthPath: 'k8s-rhte-acm-hub'
