cluster:
  name: "demo-jun1"
  baseDomain: "lab.signal9.gg"
  gitOpsRepo: "https://github.com/marbindrakon/fleet-gitops-example.git"
  gitOpsBasePath: argocd/clusters/managed-clusters

monitoring:
  enabled: true
  storageClass: standard-csi

externalSecrets:
  vaultAuthPath: "k8s-mgd-demo-jun1"

timesync:
  enabled: true
  ptp:
    enabled: true
    loadKvmModule: true
  ntpServers: []

auth:
  oidcClientID: "openshift"
  externalSecret:
    name: oauth-signal9-client-secret
    vaultName: signal9-openid

certManager:
  externalSecret:
    name: route53-key
    vaultName: signal9-route53
  solvers:
    - http01:
        ingress: {}
    - dns01:
        route53:
          # Required prior to 1.9 when this can be moved to a 
          # secret and pulled from vault like the secret key
          accessKeyID: AKIAR3Z7ELN7VLNNHZHZ
          region: us-east-1
          secretAccessKeySecretRef:
            key: secret-access-key
            name: route53-key
      selector:
        dnsZones:
          - lab.signal9.gg
