{{- if .Values.provider.providerCredsVault -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.cluster.name }}-provider-creds
  namespace: {{ .Values.cluster.name }}
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: {{ .Values.cluster.name }}-provider-creds
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.provider.providerCredsVault }}
{{- end -}}
