{{- if .Values.provider.providerCAs -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.cluster.name }}-trust
  namespace: {{ .Values.cluster.name }}
  annotations:
    argocd.argoproj.io/sync-wave: '0'
stringData:
  ca.crt: |
{{ indent 4 .Values.provider.providerCAs }}
{{ end }}
