{{- if .Values.provider.providerCAs -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.cluster.name }}-trust
  namespace: {{ .Values.cluster.name }}
  annotations:
    argocd.argoproj.io/sync-wave: '0'
stringData:
{{- if eq .Values.provider.type "OpenStack" }}
  ca.crt: |
{{ else }}
  .cacert: |
{{ end -}}
{{ indent 4 .Values.provider.providerCAs }}
{{ end }}
