apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.cluster.name }}-pull-secret
  namespace: {{ .Values.cluster.name }}
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: {{ .Values.cluster.name }}-pull-secret
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .pullsecret | toString }}"
    creationPolicy: Owner
  data:
  - secretKey: pullsecret
    remoteRef:
      key: {{ .Values.cluster.pullSecretVault }}
