apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.cluster.name }}-pull-secret
  namespace: {{ .Values.cluster.name }}
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: {{ .Values.cluster.name }}-pull-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: {{ .Values.cluster.pullSecretVault }}
