---
collections:
  - name: community.general
  - name: kubernetes.core
  - name: hpe.ilo
  - name: netbox.netbox
  - name: freeipa.ansible_freeipa
  - name: community.hashi_vault
  - name: amazon.aws
  - name: openstack.cloud
