{{- if .Values.network.hostRouting -}}
apiVersion: operator.openshift.io/v1
kind: Network
metadata:
  annotations:
    networkoperator.openshift.io/ovn-cluster-initiator: 172.18.16.40
    argocd.argoproj.io/sync-options: ServerSideApply=true,Validate=false
  name: cluster
spec:
  defaultNetwork:
    ovnKubernetesConfig:
      gatewayConfig:
        routingViaHost: true
{{- end -}}
