{{- if and .Values.odfStorage.enabled .Values.odfStorage.external -}}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ocs-external-storagecluster-ceph-rbd
  annotations:
    argocd.argoproj.io/sync-wave: '3'
    argocd.argoproj.io/sync-options: ServerSideApply=true,Validate=false,SkipDryRunOnMissingResource=true
    storageclass.kubernetes.io/is-default-class: 'true'
provisioner: openshift-storage.rbd.csi.ceph.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
{{- end -}}
