{{- if and .Values.odfStorage.external .Values.odfStorage.externalSecret -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.odfStorage.externalSecret.name }}
  namespace: openshift-storage
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: '1'
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: {{ .Values.odfStorage.externalSecret.name }}
    creationPolicy: Orphan
  dataFrom:
  - extract:
      key: {{ .Values.odfStorage.externalSecret.vaultName }}
{{- end -}}
