apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-vm
  name: test-vm
  namespace: test-vm
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  ports:
  - port: 22
    targetPort: 22
    protocol: TCP
    name: ssh
  selector:
    vm.kubevirt.io/name: "test-vm"
  type: LoadBalancer
