apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1"
    vm.kubevirt.io/validations: |
      [
        {
          "name": "minimal-required-memory",
          "path": "jsonpath::.spec.domain.resources.requests.memory",
          "rule": "integer",
          "message": "This VM requires more memory.",
          "min": 1610612736
        }
      ]
  labels:
    app: test-vm
    vm.kubevirt.io/template: rhel9-server-small
    vm.kubevirt.io/template.revision: "1"
    vm.kubevirt.io/template.version: v0.19.6
  name: test-vm
  namespace: test-vm
spec:
  dataVolumeTemplates:
  - apiVersion: cdi.kubevirt.io/v1beta1
    kind: DataVolume
    metadata:
      name: test-vm
    spec:
      source:
        registry:
          url: docker://registry.redhat.io/rhel9/rhel-guest-image@sha256:2a70e7a1fadcbc12834f939fa337d977f2d9a1857e7aeb866ae1d03603ee80c9
          pullMethod: node
      storage:
        resources:
          requests:
            storage: 50Gi
        accessModes:
          - ReadWriteOnce
        volumeMode: Filesystem
  running: true
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: small
        vm.kubevirt.io/os: rhel9
        vm.kubevirt.io/workload: server
      labels:
        kubevirt.io/domain: test-vm
        kubevirt.io/size: small
    spec:
      domain:
        cpu:
          cores: 2
          sockets: 1
          threads: 1
        devices:
          disks:
          - disk:
              bus: virtio
            name: test-vm
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - masquerade: {}
            name: default
          networkInterfaceMultiqueue: true
          rng: {}
        features:
          smm:
            enabled: true
        firmware:
          bootloader:
            efi: {}
        machine:
          type: pc-q35-rhel8.4.0
        resources:
          requests:
            memory: 8Gi
      evictionStrategy: LiveMigrate
      networks:
      - name: default
        pod: {}
      terminationGracePeriodSeconds: 180
      volumes:
      - dataVolume:
          name: test-vm
        name: test-vm
      - cloudInitNoCloud:
          userData: |-
            #cloud-config
            user: cloud-user
            ssh_authorized_keys:
              - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCg+4j4gUEdpCLLNra0QiXUPcyAcuf3R8bL9s9MabN4sWTemUYzCUURs2zfa6mG2Fkl1rWhJCoiJ8OqXmjJ6dF/MrD95UghECB4IijQDbREBnNk5xRoDkTVrYzJedEAZJzQVZPwgfuECLDseVGJr+muinI9iun2xO2o0+urIPZ6qnP37TezhCdq4lhKDE03pD7lubBcjsrcG9LaH2CRJmS4z/lJ6fDYdjdYI0lWukqZ7FSN4GYUDNZ2EnAqVGCoWYx04B4kzDzt9SWmsf9hlrvF/jdS4ZNYefa2WiTM8MqNRp97aqyBBB8pL1K5lfCfgIzXst8GVb8irFbUxKgQXqx9
        name: cloudinitdisk
