---
# cluster_platform must be set to openstack or infra_env_hybrid when using the main.yml entrypoint
cluster_platform: ""
cluster_name: ""
# cluster_state should be present or absent
cluster_state: present

openstack_platform_config:
  # The external network where Floating IPs will be allocated
  vip_network: ""

vsphere_platform_config:
  node_prefix: ""

infra_env_hybrid_config:
    # Search for baremetal nodes in Netbox will be limited to this tag
    netbox_pool_tag: "openshift-pool"
    # Prefix for netbox tag applied to cluster nodes
    netbox_cluster_tag_prefix: "ocp-cluster-"
    # IP Prefixes in CIDR notation for allocating VIP and Node IPs in Netbox
    vip_prefix: ""
    node_prefix: ""
    storage_prefix: ""
    # Storage IPs will be allocated for any interface name appearing in this list
    storage_interface_names: []
