apiVersion: cdi.kubevirt.io/v1beta1
kind: StorageProfile
metadata:
  name: standard-csi
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true,Validate=false
    argocd.argoproj.io/sync-wave: "4"
spec:
  claimPropertySets:
    - accessModes:
      - ReadWriteOnce
      volumeMode: Filesystem
  cloneStrategy: snapshot
