---
version: 1

build_arg_defaults:
  EE_BASE_IMAGE: 'quay.io/ansible/ansible-runner:stable-2.12-devel'

dependencies:
  galaxy: collections/requirements.yml
  python: python-requirements.txt
  #system: bindep.txt
