{{- if .Values.externalSecrets.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: '1'
spec:
  provider:
    vault:
      server: {{ .Values.externalSecrets.vaultBase }}
      path: {{ .Values.externalSecrets.secretBasePath }}
      version: "v2"
      auth:
        kubernetes:
          mountPath: {{ .Values.externalSecrets.vaultAuthPath }}
          role: "external-secrets-operator"
          serviceAccountRef:
            name: "external-secrets-operator"
            namespace: "external-secrets-operator"
{{ end }}
