{{- if .Values.externalSecrets.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault
spec:
  provider:
    vault:
      server: {{ .Values.externalSecrets.vaultBase }}
      path: {{ .Values.externalSecrets.secretBasePath }}
      version: "v2"
      auth:
        kubernetes:
          mountPath: {{ .Values.externalSecrets.vaultAuthPath }}
          role: "external-secrets-operator"
          serviceAccountRef:
            name: "external-secrets-operator"
            namespace: "external-secrets-operator"
{{ end }}
