{{- if .Values.externalSecrets.enabled -}}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: external-secrets-operator
  namespace: external-secrets-operator
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: external-secrets-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
{{ end }}
