apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ocp6-deploy
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: openshift-gitops
    server: "https://kubernetes.default.svc"
  ignoreDifferences:
    - group: hive.openshift.io
      kind: ClusterDeployment
      jsonPointers:
        - /spec/installed
  project: default
  syncPolicy:
    automated: {}
  source:
    repoURL: "https://github.com/marbindrakon/rhte-2023-fleet-gitops.git"
    path: "charts/mce-cluster-build"
    targetRevision: HEAD
    helm:
      valueFiles:
        - "../../argocd/clusters/managed-clusters/ocp6/helm-values/build-values.yaml"
