apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: multiclusterhub-operator-pull-secret
  namespace: open-cluster-management-observability
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: multiclusterhub-operator-pull-secret
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .pullsecret | toString }}"
    creationPolicy: Owner
  data:
  - secretKey: pullsecret
    remoteRef:
      key: 'ocp-pull-secret'
