---
apiVersion: v1
kind: Namespace
metadata:
  name: rhacm-hub
spec: {}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: rhacm-group
  namespace: rhacm-hub
spec:
  targetNamespaces:
  - rhacm-hub
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: acm-operator-subscription
  namespace: rhacm-hub
spec:
  sourceNamespace: openshift-marketplace
  source: redhat-operators
  channel: release-2.6
  installPlanApproval: Automatic
  name: advanced-cluster-management
