kind: ConfigMap
apiVersion: v1
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    alertmanagerMain:
      nodeSelector: null
      resources: null
      tolerations: null
      volumeClaimTemplate:
        metadata: {}
        spec:
          resources:
            requests:
              storage: 5Gi
          storageClassName: ocs-external-storagecluster-ceph-rbd
        status: {}
    enableUserWorkload: null
    grafana: null
    http: null
    k8sPrometheusAdapter: null
    kubeStateMetrics: null
    openshiftStateMetrics: null
    prometheusK8s:
      additionalAlertManagerConfigs:
      - apiVersion: v2
        bearerToken:
          key: token
          name: observability-alertmanager-accessor
        pathPrefix: /
        scheme: https
        staticConfigs:
        - alertmanager-open-cluster-management-observability.apps.rhte-acm-hub.lab.signal9.gg
        tlsConfig:
          ServerName: ""
          ca:
            key: service-ca.crt
            name: hub-alertmanager-router-ca
          insecureSkipVerify: false
      externalLabels:
        cluster: 2752f03d-ff94-4931-af6b-c98a27d97cd8
        managed_cluster: 2752f03d-ff94-4931-af6b-c98a27d97cd8
      logLevel: ""
      nodeSelector: null
      remoteWrite: null
      resources: null
      retention: 7d
      tolerations: null
      volumeClaimTemplate:
        metadata: {}
        spec:
          resources:
            requests:
              storage: 50Gi
          storageClassName: ocs-external-storagecluster-ceph-rbd
        status: {}
    prometheusOperator: null
    telemeterClient: null
    thanosQuerier: null
