apiVersion: agent-install.openshift.io/v1beta1
kind: AgentServiceConfig
metadata:
 name: agent
spec:
  databaseStorage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Gi
  filesystemStorage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Gi
  imageStorage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Gi
  osImages:
    - openshiftVersion: "4.8"
      cpuArchitecture: "x86_64"
      version: "48.84.202109241901-0"
      url: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.8/4.8.14/rhcos-4.8.14-x86_64-live.x86_64.iso"
    - openshiftVersion: "4.9"
      cpuArchitecture: "x86_64"
      version: "49.84.202206171736-0"
      url: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.9/4.9.40/rhcos-4.9.40-x86_64-live.x86_64.iso"
    - openshiftVersion: "4.10"
      cpuArchitecture: "x86_64"
      version: "410.84.202205191234-0"
      url: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.10/4.10.16/rhcos-4.10.16-x86_64-live.x86_64.iso"
    - openshiftVersion: "4.11"
      cpuArchitecture: "x86_64"
      version: "411.86.202210041459-0"
      url: "https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.11/4.11.9/rhcos-4.11.9-x86_64-live.x86_64.iso"
    - openshiftVersion: "4.12"
      cpuArchitecture: "x86_64"
      version: "412.86.202212081411-0"
      url: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.12/4.12.0/rhcos-4.12.0-x86_64-live.x86_64.iso"
