apiVersion: metal3.io/v1alpha1
kind: Provisioning
metadata:
  name: provisioning-configuration
spec:
  provisioningMacAddress: "ac:1f:6b:79:e3:da"
  provisioningNetwork: Disabled
  watchAllNamespaces: true
