apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hive-imagesets
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: '3'
spec:
  destination:
    namespace: openshift-gitops
    server: "https://kubernetes.default.svc"
  project: default
  syncPolicy:
    automated: {}
  source:
    repoURL: "https://github.com/stolostron/acm-hive-openshift-releases.git"
    path: "clusterImageSets/stable"
    targetRevision: "release-2.6"
    directory:
      recurse: true
