apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: base-config-chart
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: "https://kubernetes.default.svc"
  project: default
  syncPolicy:
    automated: {}
    retry:
      backoff:
        maxDuration: 1m
      limit: -1
  source:
    repoURL: "https://github.com/marbindrakon/rhte-2023-fleet-gitops.git"
    path: "charts/ocp-base-config"
    targetRevision: HEAD
    helm:
      values: |
        cluster:
          name: ocp
          baseDomain: lab.signal9.gg
          gitOpsBasePath: argocd/clusters/managed-clusters
        monitoring:
          enabled: true
          storageClass: standard-csi
        externalSecrets:
          vaultAuthPath: 'k8s-ocp'
        timesync:
          enabled: true
          ptp:
            enabled: false
            loadKvmModule: false
          ntpServers:
            - 172.18.0.79
            - 172.18.42.10
            - 172.18.42.11
        certManager:
          solvers:
            - http01:
                ingress: {}
            - dns01:
                route53:
                  # Required prior to 1.9 when this can be moved to a 
                  # secret and pulled from vault like the secret key
                  accessKeyID: AKIAR3Z7ELN7VLNNHZHZ
                  region: us-east-1
                  secretAccessKeySecretRef:
                    key: secret-access-key
                    name: route53-key
              selector:
                dnsZones:
                  - signal9.gg
                  - lab.signal9.gg
